default:
  before_script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install poetry
    - poetry install

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: make test

typecheck:
  stage: test
  script: make typecheck

lint:
  stage: test
  script: make lint

coverage:
  stage: test
  script: make coverage

quality:
  stage: test
  script: make quality

benchmark:
  stage: test
  script: make benchmark

build:
  stage: build
  script: make build

deploy:
  stage: deploy
  script:
    - make deploy
    - sleep 60  # sleep for a minute to make sure we can get build from PyPI
    - make test_deploy
  only:
    refs:
      - master
