language: python

python:
  - "3.7"
  - "3.8"

branches:
  only:
  - master
  - develop

install:
  - pip install -r requirements.txt

script:
  - make test lint typecheck coverage quality benchmark build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  python: "3.8"
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master

git:
  quiet: true
  submodules: false
