language: python

python:
  - "3.7"
  - "3.8"

branches:
  only:
  - master
  - develop

install:
  - pip install -r requirements.txt

script:
  - make test lint typecheck coverage quality benchmark build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  skip_cleanup: true
  provider: script
  script:
    - make deploy
    - sleep 60  # sleep for a minute to make sure we can get build from PyPI
    - make test_deploy
  on:
    python: "3.8"
    branch: master

git:
  quiet: true
  submodules: false
